// Script de seed des VCs français
// Lancer avec : npx tsx lib/seed-vcs.ts

process.loadEnvFile(".env.local");

import { createClient } from "@supabase/supabase-js";

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!
);

const VCS_FRANCAIS = [
  // ─────────────────────────────────────────────
  // FONDS TECH EARLY-STAGE (déjà existants)
  // ─────────────────────────────────────────────
  {
    name: "Partech Partners",
    description: "L'un des fonds VC les plus actifs en Europe, avec une forte présence en France et à l'international.",
    website: "https://partechpartners.com",
    contact_email: "contact@partechpartners.com",
    sectors: ["SaaS / Logiciel", "FinTech", "DeepTech / IA", "Marketplace", "E-commerce / Retail"],
    stages: ["Seed", "Série A", "Série B"],
    ticket_min: 500000,
    ticket_max: 30000000,
    investment_thesis: "Partech investit dans des startups technologiques ambitieuses qui adressent de grands marchés mondiaux. Le fonds cible des entrepreneurs visionnaires capables de construire des leaders européens, voire mondiaux. Partech est particulièrement attentif aux modèles SaaS B2B scalables, aux places de marché à effets de réseau forts et aux solutions d'IA appliquée. Tickets de Seed à Série B avec une préférence pour les startups déjà en traction.",
    notable_investments: "Doctolib, Swile, Back Market, ContentSquare, Lydia",
  },
  {
    name: "Kima Ventures",
    description: "Fonds de Xavier Niel, l'un des investisseurs les plus actifs au monde avec +100 deals/an.",
    website: "https://www.kimaventures.com",
    contact_email: "contact@kimaventures.com",
    sectors: ["SaaS / Logiciel", "FinTech", "Marketplace", "DeepTech / IA", "E-commerce / Retail", "Tous secteurs"],
    stages: ["Pre-seed", "Seed"],
    ticket_min: 150000,
    ticket_max: 500000,
    investment_thesis: "Kima Ventures investit très tôt (pre-seed/seed) dans des startups tech du monde entier avec un ticket standardisé. Le fonds valorise les fondateurs ambitieux avec une vision claire, un produit différenciant et une capacité d'exécution rapide. Kima ne se limite pas à un secteur particulier. Le process de décision est rapide (48h possible) et l'accompagnement est volontairement léger pour laisser la liberté aux fondateurs.",
    notable_investments: "Algolia, Front, Heetch, Lunchr (devenu Swile)",
  },
  {
    name: "Elaia Partners",
    description: "VC spécialisé dans les startups tech et deeptech françaises et européennes.",
    website: "https://www.elaia.com",
    contact_email: "contact@elaia.com",
    sectors: ["DeepTech / IA", "SaaS / Logiciel", "HealthTech / MedTech", "Cybersécurité"],
    stages: ["Seed", "Série A", "Série B"],
    ticket_min: 500000,
    ticket_max: 20000000,
    investment_thesis: "Elaia investit dans des startups tech et deeptech avec une conviction forte pour les technologies de rupture. Le fonds cible des marchés où la technologie crée un avantage compétitif durable, notamment l'IA, les logiciels d'entreprise, la cybersécurité et les medtech. Elaia accompagne les fondateurs sur le long terme avec une approche collaborative.",
    notable_investments: "Shift Technology, Akeneo, Teads, Criteo (early)",
  },
  {
    name: "ISAI",
    description: "Fonds fondé par des entrepreneurs du numérique, pour des entrepreneurs du numérique.",
    website: "https://www.isai.fr",
    contact_email: "contact@isai.fr",
    sectors: ["SaaS / Logiciel", "Marketplace", "FinTech", "E-commerce / Retail"],
    stages: ["Seed", "Série A"],
    ticket_min: 300000,
    ticket_max: 5000000,
    investment_thesis: "ISAI est un fonds géré par des entrepreneurs qui ont construit et vendu des entreprises numériques. Le fonds investit dans des startups B2B et B2C avec un modèle économique validé et une traction commerciale claire. ISAI privilégie les secteurs qu'il connaît bien : marketplace, SaaS, FinTech et e-commerce.",
    notable_investments: "Malt, Vestiaire Collective, Drivy (devenu Getaround)",
  },
  {
    name: "Serena",
    description: "VC early-stage spécialisé dans les startups B2B SaaS et marketplaces européennes.",
    website: "https://www.serena.vc",
    contact_email: "founders@serena.vc",
    sectors: ["SaaS / Logiciel", "Marketplace", "FinTech", "DeepTech / IA"],
    stages: ["Seed", "Série A"],
    ticket_min: 500000,
    ticket_max: 8000000,
    investment_thesis: "Serena investit dans des startups B2B avec une conviction pour les logiciels d'entreprise innovants et les places de marché créant de la liquidité. Le fonds cible des fondateurs techniques avec une vision produit forte et une capacité à construire des équipes de haut niveau.",
    notable_investments: "Whispeak, Implicity, Noci",
  },
  {
    name: "Daphni",
    description: "Fonds VC nouvelle génération, investissant avec une communauté d'entrepreneurs.",
    website: "https://www.daphni.com",
    contact_email: "hello@daphni.com",
    sectors: ["SaaS / Logiciel", "FinTech", "DeepTech / IA", "GreenTech / CleanTech", "HealthTech / MedTech"],
    stages: ["Seed", "Série A"],
    ticket_min: 300000,
    ticket_max: 5000000,
    investment_thesis: "Daphni est un VC communautaire qui s'appuie sur un réseau d'entrepreneurs et d'experts pour identifier, sélectionner et accompagner les startups. Le fonds investit dans des entreprises tech à fort potentiel de croissance, avec une sensibilité particulière pour l'impact positif et les technologies de rupture.",
    notable_investments: "Cityscoot, Legalstart, Agricool",
  },
  {
    name: "Eurazeo Ventures",
    description: "Branche VC d'Eurazeo, l'un des fonds les plus importants d'Europe.",
    website: "https://www.eurazeo.com/fr/activites/venture",
    contact_email: "venture@eurazeo.com",
    sectors: ["SaaS / Logiciel", "FinTech", "HealthTech / MedTech", "DeepTech / IA", "Marketplace"],
    stages: ["Série A", "Série B", "Série B+"],
    ticket_min: 5000000,
    ticket_max: 100000000,
    investment_thesis: "Eurazeo Ventures investit dans des leaders technologiques européens en forte croissance, du Série A aux late-stage. Le fonds cible des startups avec un modèle économique validé, une croissance supérieure à 50% par an et le potentiel de devenir des leaders de marché européens.",
    notable_investments: "Vestiaire Collective, ManoMano, Contentsquare, Younited Credit",
  },
  {
    name: "Bpifrance Ventures",
    description: "Bras VC de la banque publique d'investissement française.",
    website: "https://www.bpifrance.fr",
    contact_email: "innovation@bpifrance.fr",
    sectors: ["DeepTech / IA", "HealthTech / MedTech", "GreenTech / CleanTech", "SaaS / Logiciel", "Tous secteurs"],
    stages: ["Pre-seed", "Seed", "Série A", "Série B"],
    ticket_min: 100000,
    ticket_max: 50000000,
    investment_thesis: "Bpifrance soutient l'innovation française à tous les stades, depuis la R&D jusqu'aux grandes levées de fonds. Le fonds investit dans des entreprises innovantes créant de la valeur pour l'économie française, avec une attention particulière pour la deeptech, la souveraineté technologique, la santé et la transition écologique.",
    notable_investments: "OVHcloud, Voodoo, Alan",
  },
  {
    name: "Alven Capital",
    description: "VC early-stage parmi les plus reconnus de l'écosystème tech français.",
    website: "https://www.alven.co",
    contact_email: "contact@alven.co",
    sectors: ["SaaS / Logiciel", "Marketplace", "FinTech", "E-commerce / Retail", "DeepTech / IA"],
    stages: ["Seed", "Série A"],
    ticket_min: 500000,
    ticket_max: 10000000,
    investment_thesis: "Alven Capital investit depuis 2000 dans les startups tech françaises et européennes les plus prometteuses. Le fonds est généraliste avec une forte expertise sur les marketplaces, le SaaS B2B et les nouvelles plateformes digitales. Alven valorise les équipes fondatrices exceptionnelles avec une vision à long terme.",
    notable_investments: "Frichti, Zenly (acquired by Snap), Priceminister",
  },
  {
    name: "Singular (ex-360 Capital)",
    description: "VC franco-italien spécialisé dans les startups tech early-stage.",
    website: "https://singular.vc",
    contact_email: "hello@singular.vc",
    sectors: ["SaaS / Logiciel", "DeepTech / IA", "FinTech", "Marketplace"],
    stages: ["Pre-seed", "Seed", "Série A"],
    ticket_min: 200000,
    ticket_max: 6000000,
    investment_thesis: "Singular investit dans les startups technologiques ambitieuses dès les premiers stades. Le fonds cherche des fondateurs capables de construire des entreprises globales depuis l'Europe, avec une thèse forte sur les opportunités créées par l'IA et la transformation digitale des industries.",
    notable_investments: "Meero, Joko, Indy, Memo Bank",
  },
  {
    name: "Newfund",
    description: "VC franco-américain early-stage avec une présence forte à Paris et San Francisco.",
    website: "https://www.newfundcap.com",
    contact_email: "info@newfundcap.com",
    sectors: ["SaaS / Logiciel", "FinTech", "DeepTech / IA", "HealthTech / MedTech"],
    stages: ["Pre-seed", "Seed"],
    ticket_min: 200000,
    ticket_max: 2000000,
    investment_thesis: "Newfund est un fonds bi-continental (Paris / SF) qui investit dans des startups tech avec ambition internationale. Le fonds cible des entrepreneurs qui pensent global avec le potentiel d'adresser des marchés américains et européens simultanément. Accompagnement actif pour le go-to-market aux États-Unis.",
    notable_investments: "Lifen, Modjo",
  },
  {
    name: "Iris Capital",
    description: "VC franco-allemand investissant dans les startups tech à fort potentiel européen.",
    website: "https://www.iriscapital.com",
    contact_email: "contact@iriscapital.com",
    sectors: ["SaaS / Logiciel", "FinTech", "Marketplace", "E-commerce / Retail", "DeepTech / IA"],
    stages: ["Série A", "Série B"],
    ticket_min: 2000000,
    ticket_max: 25000000,
    investment_thesis: "Iris Capital gère des fonds avec Orange et Publicis comme LPs stratégiques, offrant aux startups un accès unique aux réseaux Telecom et Communication mondiaux. Le fonds investit dans des startups tech en Série A/B avec un modèle commercial validé et une croissance forte.",
    notable_investments: "Believe, SumUp, Adjust",
  },
  {
    name: "Axeleo Capital",
    description: "VC spécialisé dans les startups B2B SaaS et DeepTech.",
    website: "https://www.axeleo.com",
    contact_email: "contact@axeleo.com",
    sectors: ["SaaS / Logiciel", "DeepTech / IA", "Cybersécurité", "FinTech"],
    stages: ["Seed", "Série A"],
    ticket_min: 300000,
    ticket_max: 5000000,
    investment_thesis: "Axeleo Capital investit dans des startups B2B tech innovantes avec une conviction forte pour les logiciels verticaux, l'IA appliquée aux entreprises et la cybersécurité. Le fonds s'appuie sur un réseau de +200 scale-up et grands groupes pour co-construire les go-to-market.",
    notable_investments: "DataGalaxy, Jalgos",
  },
  {
    name: "Ring Capital",
    description: "VC fondé par des entrepreneurs pour des entrepreneurs, focalisé sur la croissance.",
    website: "https://www.ring.capital",
    contact_email: "hello@ring.capital",
    sectors: ["SaaS / Logiciel", "Marketplace", "FinTech", "E-commerce / Retail"],
    stages: ["Série A", "Série B"],
    ticket_min: 2000000,
    ticket_max: 20000000,
    investment_thesis: "Ring Capital investit dans des startups tech en forte croissance avec des business models éprouvés. Le fonds est fondé et géré par des serial entrepreneurs qui apportent une vision opérationnelle unique. Ring valorise les startups avec une NRR >120% et une expansion géographique claire.",
    notable_investments: "Payplug, Brainly, Botify",
  },
  {
    name: "Blast.club",
    description: "Club d'investisseurs business angels organisés, spécialisés dans le early-stage français.",
    website: "https://www.blast.club",
    contact_email: "contact@blast.club",
    sectors: ["SaaS / Logiciel", "Marketplace", "FinTech", "DeepTech / IA", "Tous secteurs"],
    stages: ["Pre-seed", "Seed"],
    ticket_min: 100000,
    ticket_max: 1000000,
    investment_thesis: "Blast Club rassemble une communauté d'investisseurs expérimentés qui co-investissent dans les meilleures startups françaises early-stage. Le club investit dans tous les secteurs tech avec une priorité pour les modèles innovants. L'approche collective permet une due diligence plus riche.",
    notable_investments: "Pennylane, Luko, Alma",
  },
  {
    name: "Otium Capital",
    description: "Family office et fonds VC focalisé sur la tech et les startups à impact.",
    website: "https://www.otiumcap.com",
    contact_email: "contact@otiumcap.com",
    sectors: ["SaaS / Logiciel", "FinTech", "GreenTech / CleanTech", "EdTech", "Marketplace"],
    stages: ["Seed", "Série A"],
    ticket_min: 200000,
    ticket_max: 5000000,
    investment_thesis: "Otium Capital est le fonds d'investissement du fondateur de PriceMinister. Le fonds investit dans des startups tech françaises avec un focus sur les modèles marketplace, SaaS et les startups à impact positif. Otium apporte une expertise unique dans la construction de marketplaces.",
    notable_investments: "Legalstart, Gymlib, Coorpacademy",
  },
  {
    name: "Founders Future",
    description: "Fonds seed fondé par Marc Menasé, investi dans +150 startups françaises.",
    website: "https://www.foundersfuture.com",
    contact_email: "contact@foundersfuture.com",
    sectors: ["SaaS / Logiciel", "FinTech", "Marketplace", "E-commerce / Retail", "DeepTech / IA", "Tous secteurs"],
    stages: ["Pre-seed", "Seed"],
    ticket_min: 100000,
    ticket_max: 1500000,
    investment_thesis: "Founders Future est un fonds early-stage qui accompagne les meilleurs entrepreneurs dès les premiers stades. Le fonds investit rapidement et est généraliste avec une préférence pour les business models innovants qui transforment des industries traditionnelles.",
    notable_investments: "Blank, Sunday",
  },
  {
    name: "Verve Ventures",
    description: "VC suisse actif en France pour les startups deeptech et healthtech.",
    website: "https://www.verve.vc",
    contact_email: "info@verve.vc",
    sectors: ["DeepTech / IA", "HealthTech / MedTech", "Cybersécurité", "GreenTech / CleanTech"],
    stages: ["Seed", "Série A"],
    ticket_min: 500000,
    ticket_max: 10000000,
    investment_thesis: "Verve Ventures s'appuie sur une communauté de +2000 business angels experts pour investir dans les startups deeptech et healthtech les plus prometteuses. Le fonds cible des startups avec une forte propriété intellectuelle et une barrière technologique élevée.",
    notable_investments: "Sophia Genetics, Open Mind Neurotechnologies",
  },
  {
    name: "Cathay Innovation",
    description: "VC global franco-chinois avec une forte présence en Europe et en Asie.",
    website: "https://www.cathayinnovation.com",
    contact_email: "contact@cathayinnovation.com",
    sectors: ["DeepTech / IA", "HealthTech / MedTech", "GreenTech / CleanTech", "SaaS / Logiciel", "FinTech"],
    stages: ["Série A", "Série B", "Série B+"],
    ticket_min: 5000000,
    ticket_max: 50000000,
    investment_thesis: "Cathay Innovation investit dans des startups tech à fort impact en Europe, aux US et en Asie. Le fonds cible des startups Series A+ avec des business models validés et le potentiel d'expansion internationale rapide, notamment vers les marchés asiatiques.",
    notable_investments: "Ÿnsect, Shift Technology, Deezer",
  },
  {
    name: "Crédit Mutuel Innovation",
    description: "Bras VC du groupe bancaire Crédit Mutuel Arkéa, focalisé sur la FinTech.",
    website: "https://www.arkea.com",
    contact_email: "innovation@cma.fr",
    sectors: ["FinTech", "SaaS / Logiciel", "Cybersécurité", "InsurTech / Assurance"],
    stages: ["Seed", "Série A", "Série B"],
    ticket_min: 500000,
    ticket_max: 15000000,
    investment_thesis: "Crédit Mutuel Innovation investit dans des startups FinTech et tech qui transforment les services financiers et bancaires. Le fonds apporte un accès aux clients bancaires du groupe, une expertise réglementaire financière et des canaux de distribution.",
    notable_investments: "Leetchi, Pumpkin, Budget Insight",
  },
  {
    name: "Stride VC",
    description: "VC seed spécialisé dans les startups B2B SaaS et API-first.",
    website: "https://stride.vc",
    contact_email: "pitch@stride.vc",
    sectors: ["SaaS / Logiciel", "DeepTech / IA", "Cybersécurité", "FinTech"],
    stages: ["Pre-seed", "Seed"],
    ticket_min: 200000,
    ticket_max: 3000000,
    investment_thesis: "Stride VC investit dans les meilleures startups B2B tech européennes dès les premières heures. Le fonds a une conviction forte pour les infrastructures techniques (API, outils développeurs, données), les logiciels verticaux B2B et les startups qui construisent le futur du travail.",
    notable_investments: "Shipup, Pliant",
  },
  {
    name: "Gaia Capital Partners",
    description: "VC spécialisé dans les startups de la transition énergétique et climatique.",
    website: "https://gaiacapitalpartners.com",
    contact_email: "contact@gaiacapitalpartners.com",
    sectors: ["GreenTech / CleanTech", "DeepTech / IA", "FoodTech / AgriTech", "Énergie"],
    stages: ["Seed", "Série A"],
    ticket_min: 300000,
    ticket_max: 8000000,
    investment_thesis: "Gaia Capital Partners investit exclusivement dans des startups contribuant à la transition énergétique et à la lutte contre le changement climatique. Le fonds cible des solutions tech innovantes dans l'énergie renouvelable, l'efficacité énergétique, la mobilité durable et l'agriculture régénérative.",
    notable_investments: "Agregio, Zenon",
  },
  {
    name: "Seventure Partners",
    description: "VC spécialisé dans les life sciences et la santé digitale.",
    website: "https://www.seventure.fr",
    contact_email: "contact@seventure.fr",
    sectors: ["HealthTech / MedTech", "FoodTech / AgriTech", "DeepTech / IA"],
    stages: ["Seed", "Série A", "Série B"],
    ticket_min: 500000,
    ticket_max: 20000000,
    investment_thesis: "Seventure Partners est un VC spécialisé dans les sciences de la vie avec +20 ans d'expérience. Le fonds investit dans des startups en biotechnologie, medtech, santé digitale et nutrition/microbiome. Seventure apporte une expertise scientifique approfondie et un réseau de KOLs médicaux.",
    notable_investments: "LVL Technologies, Mnemo Therapeutics",
  },
  {
    name: "Benhamou Global Ventures",
    description: "VC franco-américain focalisé sur les entreprises deeptech et IA.",
    website: "https://www.bgv.vc",
    contact_email: "contact@bgv.vc",
    sectors: ["DeepTech / IA", "Cybersécurité", "SaaS / Logiciel", "HealthTech / MedTech"],
    stages: ["Seed", "Série A"],
    ticket_min: 500000,
    ticket_max: 10000000,
    investment_thesis: "BGV est fondé par Eric Benhamou (ex-3Com, Palm) et investit dans des startups deeptech avec une forte composante IA. Le fonds cible des technologies de rupture dans la sécurité, l'IA enterprise, les semi-conducteurs et les interfaces homme-machine.",
    notable_investments: "Elysia Capital, Alsee",
  },
  {
    name: "Korelya Capital",
    description: "VC franco-coréen ciblant les startups tech avec potentiel asiatique.",
    website: "https://www.korelya.com",
    contact_email: "contact@korelya.com",
    sectors: ["SaaS / Logiciel", "E-commerce / Retail", "FinTech", "DeepTech / IA"],
    stages: ["Série A", "Série B"],
    ticket_min: 3000000,
    ticket_max: 30000000,
    investment_thesis: "Korelya Capital est un fonds franco-coréen soutenu par Naver qui investit dans des startups tech européennes avec un potentiel en Asie. Accès aux marchés coréen et japonais, partenariats avec Naver et Line. Cible des Série A/B avec un modèle validé en Europe.",
    notable_investments: "Meero, Tictactrip",
  },
  {
    name: "Frst (ex-eFounders VC)",
    description: "VC du studio de startups eFounders, investi dans des startups SaaS B2B.",
    website: "https://www.frst.vc",
    contact_email: "hello@frst.vc",
    sectors: ["SaaS / Logiciel", "FinTech", "Marketplace", "RH / Recrutement"],
    stages: ["Pre-seed", "Seed"],
    ticket_min: 200000,
    ticket_max: 2000000,
    investment_thesis: "Frst est le fonds externe d'eFounders, le studio qui a créé Front, Aircall et Spendesk. Le fonds investit dans les meilleures startups SaaS B2B européennes en apportant l'expertise opérationnelle acquise dans la construction de +25 startups.",
    notable_investments: "Modjo, Swan, Cycle",
  },
  {
    name: "Brighteye Ventures",
    description: "Le seul VC européen 100% focalisé sur l'EdTech.",
    website: "https://brighteyevc.com",
    contact_email: "hello@brighteyevc.com",
    sectors: ["EdTech", "SaaS / Logiciel", "DeepTech / IA", "RH / Recrutement"],
    stages: ["Seed", "Série A"],
    ticket_min: 500000,
    ticket_max: 8000000,
    investment_thesis: "Brighteye Ventures est le premier VC européen entièrement dédié à l'EdTech. Le fonds investit dans des startups qui transforment l'éducation, la formation professionnelle et le développement des compétences. Brighteye cible des modèles scalables avec un impact mesurable sur les résultats d'apprentissage.",
    notable_investments: "Coorpacademy, Lalilo",
  },
  {
    name: "Raise Ventures",
    description: "VC fondé par des serial entrepreneurs, spécialisé en impact positif.",
    website: "https://www.raise-impact.com",
    contact_email: "contact@raise-impact.com",
    sectors: ["GreenTech / CleanTech", "HealthTech / MedTech", "EdTech", "SaaS / Logiciel", "Tous secteurs"],
    stages: ["Seed", "Série A"],
    ticket_min: 300000,
    ticket_max: 5000000,
    investment_thesis: "Raise Ventures investit dans des startups à fort impact positif qui sont également de bons business. Le fonds a une conviction que les entreprises les plus performantes du futur aligneront profit et impact. Cible des startups avec une mission claire et un modèle économique viable.",
    notable_investments: "Phenix, Shapr, Agriconomie",
  },
  {
    name: "Motier Ventures",
    description: "Family office de la famille Moulin (Galeries Lafayette) investi en tech.",
    website: "https://www.motier.vc",
    contact_email: "contact@motier.vc",
    sectors: ["E-commerce / Retail", "PropTech / Immobilier", "SaaS / Logiciel", "Marketplace", "Mode / Luxe"],
    stages: ["Seed", "Série A"],
    ticket_min: 300000,
    ticket_max: 5000000,
    investment_thesis: "Motier Ventures est le family office tech de la famille Moulin, propriétaire des Galeries Lafayette. Le fonds investit dans des startups tech qui transforment le retail, l'immobilier et les services aux entreprises. Accès unique au groupe Galeries Lafayette comme client pilote et réseau retail premium.",
    notable_investments: "Alan (early), Ornikar, Brigad",
  },
  {
    name: "Hi Inov",
    description: "VC de BNP Paribas Développement spécialisé dans les startups FinTech et tech.",
    website: "https://www.hi-inov.com",
    contact_email: "contact@hi-inov.com",
    sectors: ["FinTech", "Cybersécurité", "SaaS / Logiciel", "DeepTech / IA", "InsurTech / Assurance"],
    stages: ["Seed", "Série A", "Série B"],
    ticket_min: 500000,
    ticket_max: 15000000,
    investment_thesis: "Hi Inov est le fonds de corporate venture de BNP Paribas. Le fonds investit dans des startups tech qui créent de la valeur dans les services financiers, la banque digitale et l'infrastructure FinTech. Accès au groupe BNP Paribas dans 72 pays.",
    notable_investments: "Lydia, Younited Credit",
  },
  {
    name: "Techstars Paris",
    description: "Programme d'accélération mondial avec investissement seed systématique.",
    website: "https://www.techstars.com/accelerators/paris",
    contact_email: "paris@techstars.com",
    sectors: ["SaaS / Logiciel", "FinTech", "DeepTech / IA", "Marketplace", "Tous secteurs"],
    stages: ["Pre-seed", "Seed"],
    ticket_min: 120000,
    ticket_max: 120000,
    investment_thesis: "Techstars Paris est l'antenne française du plus grand réseau d'accélération mondial. Le programme offre 120K$, 3 mois d'accompagnement intensif et un accès au réseau Techstars de +10 000 mentors. Sélectionne les équipes les plus prometteuses tous secteurs confondus.",
    notable_investments: "Hivebrite, Classez-moi",
  },

  // ─────────────────────────────────────────────
  // NOUVEAUX FONDS TECH
  // ─────────────────────────────────────────────
  {
    name: "Breega",
    description: "VC pan-européen fondé par des entrepreneurs pour des entrepreneurs, early-stage.",
    website: "https://www.breega.com",
    contact_email: "com@breega.com",
    sectors: ["SaaS / Logiciel", "FinTech", "DeepTech / IA", "GreenTech / CleanTech", "HealthTech / MedTech", "Cybersécurité"],
    stages: ["Pre-seed", "Seed", "Série A"],
    ticket_min: 500000,
    ticket_max: 15000000,
    investment_thesis: "Breega investit dans des startups pre-Seed à Série A+ en Europe et en Afrique, en travaillant exclusivement avec des fondateurs ayant déjà construit ou opéré des entreprises. Au-delà du capital, l'équipe apporte un support opérationnel en business development, marketing, RH et juridique pour accélérer la croissance.",
    notable_investments: "WayKonect, Ponicode, Lylo",
  },
  {
    name: "Ventech",
    description: "VC pionnier européen fondé en 1998, approche sectorielle large et portée mondiale.",
    website: "https://www.ventechvc.com",
    contact_email: "contact@ventechvc.com",
    sectors: ["SaaS / Logiciel", "FinTech", "DeepTech / IA", "Marketplace", "HealthTech / MedTech"],
    stages: ["Seed", "Série A", "Série B"],
    ticket_min: 1000000,
    ticket_max: 10000000,
    investment_thesis: "Ventech investit dans des startups early-stage B2B et B2C en Europe et en Asie avec une approche sectorielle large couvrant software et hardware. Avec des bureaux à Paris, Munich, Helsinki et Shanghai, Ventech offre un accès unique aux marchés européens et asiatiques.",
    notable_investments: "Dailymotion (early), Mirakl (early)",
  },
  {
    name: "XAnge",
    description: "VC early-stage adossé à La Banque Postale, spécialisé dans les startups digitales.",
    website: "https://www.xange.fr",
    contact_email: "contact@xange.fr",
    sectors: ["SaaS / Logiciel", "FinTech", "Marketplace", "E-commerce / Retail", "DeepTech / IA"],
    stages: ["Pre-seed", "Seed", "Série A"],
    ticket_min: 200000,
    ticket_max: 8000000,
    investment_thesis: "XAnge investit dans les meilleures startups tech françaises early-stage avec un focus particulier sur les innovations digitales qui transforment les services et le commerce. Adossé à La Banque Postale, XAnge apporte des ressources institutionnelles uniques et un réseau de distribution.",
    notable_investments: "Alkemics, JobTeaser, Whyd",
  },
  {
    name: "Sofinnova Partners",
    description: "VC européen de référence spécialisé dans les sciences de la vie et la biotech.",
    website: "https://www.sofinnova.fr",
    contact_email: "contact@sofinnova.fr",
    sectors: ["HealthTech / MedTech", "DeepTech / IA", "GreenTech / CleanTech"],
    stages: ["Seed", "Série A", "Série B"],
    ticket_min: 1000000,
    ticket_max: 30000000,
    investment_thesis: "Sofinnova Partners est l'un des premiers VCs européens spécialisés dans les sciences de la vie, avec 50 ans d'expérience. Le fonds investit dans la biotechnologie, la medtech et les technologies de santé innovantes. L'expertise scientifique et le réseau médical international de Sofinnova sont des atouts majeurs.",
    notable_investments: "DBV Technologies, Flamel Technologies, Transgene",
  },
  {
    name: "Omnes Capital",
    description: "VC spécialisé dans la transition numérique et la transition énergétique.",
    website: "https://www.omnescapital.com",
    contact_email: "contact@omnescapital.com",
    sectors: ["GreenTech / CleanTech", "HealthTech / MedTech", "SaaS / Logiciel", "Énergie", "DeepTech / IA"],
    stages: ["Seed", "Série A", "Série B"],
    ticket_min: 500000,
    ticket_max: 20000000,
    investment_thesis: "Omnes Capital investit dans la transformation numérique et la transition énergétique avec des convictions fortes sur l'impact positif. Le fonds accompagne des startups innovantes qui adressent les grands défis environnementaux et sanitaires avec des solutions technologiques disruptives.",
    notable_investments: "Ecosia, Sunna Design, Ynsect",
  },
  {
    name: "Andera Partners",
    description: "Fonds alternatif français multi-stratégie : VC, Private Equity et dette.",
    website: "https://www.anderapartners.com",
    contact_email: "contact@anderapartners.com",
    sectors: ["HealthTech / MedTech", "DeepTech / IA", "SaaS / Logiciel", "E-commerce / Retail", "Services B2B"],
    stages: ["Série A", "Série B", "Série B+"],
    ticket_min: 2000000,
    ticket_max: 50000000,
    investment_thesis: "Andera Partners (ex-Edmond de Rothschild Investment Partners) est un gestionnaire alternatif multi-classe d'actifs. Le fonds venture s'intéresse aux scale-ups digitales et aux startups life sciences avec des modèles économiques validés et une trajectoire de croissance claire.",
    notable_investments: "Doctolib (early), Meero",
  },
  {
    name: "CapHorn Invest",
    description: "VC spécialisé dans la transformation digitale B2B des industries traditionnelles.",
    website: "https://www.caphorn.io",
    contact_email: "contact@caphorn.io",
    sectors: ["SaaS / Logiciel", "DeepTech / IA", "Industrie / Manufacturing", "Services B2B", "Mobilité / Transport"],
    stages: ["Seed", "Série A"],
    ticket_min: 300000,
    ticket_max: 8000000,
    investment_thesis: "CapHorn Invest accompagne la transformation digitale des industries françaises en investissant dans des startups B2B innovantes. Le fonds cible des solutions logicielles qui modernisent des secteurs traditionnels comme l'industrie, la logistique, la construction et les services aux entreprises.",
    notable_investments: "Whoz, Expliseat, Flexio",
  },
  {
    name: "Entrepreneur First",
    description: "Programme mondial qui co-fonde des startups deeptech avec des talents individuels.",
    website: "https://www.joinef.com",
    contact_email: "paris@joinef.com",
    sectors: ["DeepTech / IA", "HealthTech / MedTech", "Cybersécurité", "SaaS / Logiciel", "Tous secteurs"],
    stages: ["Pre-seed"],
    ticket_min: 80000,
    ticket_max: 500000,
    investment_thesis: "Entrepreneur First est unique : le programme recrute des individus exceptionnels (pas des équipes) avant même qu'ils aient une idée, puis les aide à se rencontrer, co-fonder et construire des startups ambitieuses. EF cible des talents avec une expertise technique profonde ou sectorielle rare pour créer des deeptech à impact mondial.",
    notable_investments: "Tractable, Magic Pony Technology, Cleo",
  },
  {
    name: "Supernova Invest",
    description: "VC spécialisé dans les startups de la transition énergétique et de la santé.",
    website: "https://www.supernova-invest.com",
    contact_email: "contact@supernova-invest.com",
    sectors: ["GreenTech / CleanTech", "HealthTech / MedTech", "DeepTech / IA", "Énergie", "Industrie / Manufacturing"],
    stages: ["Seed", "Série A", "Série B"],
    ticket_min: 500000,
    ticket_max: 15000000,
    investment_thesis: "Supernova Invest (ex-Cap Décisif) accompagne depuis 15 ans les startups innovantes dans la santé et la transition énergétique. Le fonds s'appuie sur une expertise sectorielle forte et des partenariats industriels pour accélérer la commercialisation de technologies de rupture.",
    notable_investments: "Envision, Elogen, Innothera",
  },
  {
    name: "Demeter Investissement",
    description: "VC pionnier et leader de l'investissement dans les startups de la transition écologique.",
    website: "https://www.demeter.fr",
    contact_email: "contact@demeter.fr",
    sectors: ["GreenTech / CleanTech", "FoodTech / AgriTech", "Énergie", "Mobilité / Transport", "DeepTech / IA"],
    stages: ["Seed", "Série A", "Série B"],
    ticket_min: 500000,
    ticket_max: 20000000,
    investment_thesis: "Demeter Investissement est le VC de référence en France pour les investissements dans la transition écologique. Depuis 2005, Demeter accompagne des startups innovantes dans les énergies renouvelables, l'efficacité énergétique, l'agriculture durable, la mobilité propre et l'économie circulaire.",
    notable_investments: "Voltalia, Ecotechnilin, Siège vert",
  },
  {
    name: "Karista",
    description: "VC spécialisé dans le financement des startups et PME innovantes en santé.",
    website: "https://www.karista.fr",
    contact_email: "contact@karista.fr",
    sectors: ["HealthTech / MedTech", "DeepTech / IA", "InsurTech / Assurance"],
    stages: ["Seed", "Série A"],
    ticket_min: 300000,
    ticket_max: 5000000,
    investment_thesis: "Karista investit dans des startups et PME innovantes dans le domaine de la santé : medtech, santé digitale, diagnostics, thérapeutiques et bien-être. Le fonds apporte une expertise médicale et réglementaire (CE, FDA) unique ainsi qu'un réseau de professionnels de santé pour faciliter l'adoption.",
    notable_investments: "Voluntis, DreamQuark",
  },
  {
    name: "Citizen Capital",
    description: "Premier fonds VC impact en France, investissant dans des startups à mission sociale.",
    website: "https://www.citizencapital.fr",
    contact_email: "contact@citizencapital.fr",
    sectors: ["Tous secteurs", "EdTech", "HealthTech / MedTech", "Services B2B", "GreenTech / CleanTech"],
    stages: ["Seed", "Série A"],
    ticket_min: 300000,
    ticket_max: 5000000,
    investment_thesis: "Citizen Capital est le pionnier du VC impact en France, investissant dans des startups qui combinent performance économique et impact social ou environnemental positif. Le fonds cible des modèles économiques qui bénéficient directement aux populations vulnérables, à l'éducation, à la santé accessible et à l'inclusion.",
    notable_investments: "Simplon.co, Cité Fertile, Sauvegarde",
  },
  {
    name: "Revaia",
    description: "VC growth spécialisé dans les scale-ups B2B tech durables.",
    website: "https://www.revaia.com",
    contact_email: "contact@revaia.com",
    sectors: ["SaaS / Logiciel", "FinTech", "DeepTech / IA", "GreenTech / CleanTech", "Marketplace"],
    stages: ["Série A", "Série B", "Série B+"],
    ticket_min: 5000000,
    ticket_max: 50000000,
    investment_thesis: "Revaia (ex-Gaia Growth) investit en growth dans des scale-ups B2B tech en forte croissance qui intègrent la durabilité dans leur modèle. Le fonds cible des entreprises avec un ARR de 5M€+ et une croissance supérieure à 50% qui adressent de grands marchés européens.",
    notable_investments: "Pennylane, Descartes Underwriting",
  },
  {
    name: "Go Capital",
    description: "VC régional basé à Rennes, investissant dans les startups de l'Ouest de la France.",
    website: "https://www.go-capital.fr",
    contact_email: "contact@go-capital.fr",
    sectors: ["SaaS / Logiciel", "DeepTech / IA", "HealthTech / MedTech", "FoodTech / AgriTech", "Cybersécurité"],
    stages: ["Pre-seed", "Seed", "Série A"],
    ticket_min: 200000,
    ticket_max: 5000000,
    investment_thesis: "Go Capital est un fonds régional de référence dans l'Ouest de la France (Bretagne, Pays de la Loire, Normandie). Le fonds investit dans des startups tech innovantes avec une préférence pour les modèles B2B. Go Capital apporte un accompagnement de proximité et un réseau dense d'entrepreneurs et d'industriels régionaux.",
    notable_investments: "Kerlink, Vity Technology",
  },

  // ─────────────────────────────────────────────
  // CORPORATE VCs
  // ─────────────────────────────────────────────
  {
    name: "Orange Ventures",
    description: "Fonds de corporate venture d'Orange, spécialisé dans la tech et le numérique.",
    website: "https://www.orangeventures.com",
    contact_email: "contact@orangeventures.com",
    sectors: ["SaaS / Logiciel", "DeepTech / IA", "FinTech", "Cybersécurité", "Mobilité / Transport"],
    stages: ["Seed", "Série A", "Série B"],
    ticket_min: 500000,
    ticket_max: 20000000,
    investment_thesis: "Orange Ventures est le fonds de corporate venture d'Orange, avec accès à 300M de clients dans 27 pays. Le fonds investit dans des startups tech avec un potentiel de collaboration commerciale avec le groupe Orange. Secteurs prioritaires : connectivité, cybersécurité, IA, services financiers mobiles et smart cities.",
    notable_investments: "Sigfox, Kayrros, Nexthink",
  },
  {
    name: "AXA Venture Partners",
    description: "VC du groupe AXA, investissant dans les InsurTech, HealthTech et FinTech.",
    website: "https://www.axavp.com",
    contact_email: "contact@axavp.com",
    sectors: ["InsurTech / Assurance", "HealthTech / MedTech", "FinTech", "DeepTech / IA", "Cybersécurité"],
    stages: ["Série A", "Série B", "Série B+"],
    ticket_min: 2000000,
    ticket_max: 30000000,
    investment_thesis: "AXA Venture Partners est le fonds VC du groupe AXA, l'un des premiers assureurs mondiaux. Le fonds investit dans des startups qui transforment l'assurance, la santé et les services financiers. Les startups bénéficient d'un accès direct aux clients et opérations d'AXA dans 60 pays.",
    notable_investments: "Alan, Shift Technology, Back Market",
  },
  {
    name: "MAIF Avenir",
    description: "Fonds d'investissement de la MAIF, spécialisé en mobilité et économie responsable.",
    website: "https://www.maif-avenir.fr",
    contact_email: "contact@maif-avenir.fr",
    sectors: ["Mobilité / Transport", "InsurTech / Assurance", "DeepTech / IA", "GreenTech / CleanTech", "Services B2B"],
    stages: ["Seed", "Série A", "Série B"],
    ticket_min: 300000,
    ticket_max: 10000000,
    investment_thesis: "MAIF Avenir est le fonds d'investissement de la MAIF, mutuelle d'assurance engagée. Le fonds investit dans des startups innovantes dans la mobilité, l'assurance digitale et l'économie collaborative et responsable. Les startups bénéficient de l'expertise assurantielle et du réseau de la MAIF.",
    notable_investments: "Blablacar (early), Ouicar, Koolicar",
  },
  {
    name: "Société Générale Ventures",
    description: "Fonds de corporate venture de Société Générale, focalisé sur la FinTech et la RegTech.",
    website: "https://www.sgventures.com",
    contact_email: "sgventures@socgen.com",
    sectors: ["FinTech", "Cybersécurité", "SaaS / Logiciel", "DeepTech / IA", "LegalTech / RegTech"],
    stages: ["Seed", "Série A", "Série B"],
    ticket_min: 500000,
    ticket_max: 15000000,
    investment_thesis: "Société Générale Ventures investit dans des startups qui transforment les services financiers, la banque et la finance d'entreprise. Les startups bénéficient d'un accès au groupe SG dans 67 pays, de pilotes commerciaux avec les entités du groupe et d'une crédibilité institutionnelle forte dans les secteurs régulés.",
    notable_investments: "Treezor, Lumo",
  },
  {
    name: "Capgemini Ventures",
    description: "Bras VC de Capgemini, investissant dans les startups de la transformation digitale.",
    website: "https://www.capgemini.com/fr-fr/notre-groupe/capgemini-ventures",
    contact_email: "ventures@capgemini.com",
    sectors: ["SaaS / Logiciel", "DeepTech / IA", "Cybersécurité", "Industrie / Manufacturing", "Services B2B"],
    stages: ["Seed", "Série A", "Série B"],
    ticket_min: 500000,
    ticket_max: 10000000,
    investment_thesis: "Capgemini Ventures investit dans des startups tech qui accélèrent la transformation numérique des grandes entreprises. Les startups bénéficient de l'accès au réseau client de Capgemini (Fortune 500 dans 50 pays), d'une distribution commerciale massive et d'une co-innovation avec les équipes R&D du groupe.",
    notable_investments: "Akeneo, Dataiku",
  },

  // ─────────────────────────────────────────────
  // VCs MODE / LUXE / CONSUMER
  // ─────────────────────────────────────────────
  {
    name: "L Catterton (Paris)",
    description: "Le plus grand VC mondial dédié au secteur du luxe et des biens de consommation premium.",
    website: "https://www.lcatterton.com",
    contact_email: "info@lcatterton.com",
    sectors: ["Mode / Luxe", "Cosmétique / Beauté", "E-commerce / Retail", "Sport & Lifestyle", "Restauration / FoodService"],
    stages: ["Série A", "Série B", "Série B+"],
    ticket_min: 5000000,
    ticket_max: 100000000,
    investment_thesis: "L Catterton, co-fundé par LVMH, est le leader mondial du capital-investissement dans le secteur du luxe, de la mode et des biens de consommation premium. Le fonds investit dans des marques et plateformes avec un fort potentiel de croissance dans les secteurs de la mode, beauté, gastronomie, sport et bien-être haut de gamme.",
    notable_investments: "Peloton, Equinox, Sweaty Betty, Savage X Fenty",
  },
  {
    name: "Kering Ventures",
    description: "Bras VC du groupe Kering (Gucci, Saint Laurent), spécialisé en mode durable et innovation.",
    website: "https://www.kering.com",
    contact_email: "ventures@kering.com",
    sectors: ["Mode / Luxe", "GreenTech / CleanTech", "E-commerce / Retail", "DeepTech / IA", "Marketplace"],
    stages: ["Seed", "Série A", "Série B"],
    ticket_min: 1000000,
    ticket_max: 20000000,
    investment_thesis: "Kering Ventures investit dans des startups qui révolutionnent la mode et le luxe durables, la technologie de création et la distribution innovante. Focus sur les innovations en matériaux durables, les plateformes de revente de luxe, la personnalisation par IA et les nouvelles formes d'expression créative.",
    notable_investments: "Vestiaire Collective, Reflaunt, EON",
  },
  {
    name: "Founders Group Fashion",
    description: "VC spécialisé dans les startups de la mode, du retail et de l'e-commerce.",
    website: "https://www.foundersgroup.vc",
    contact_email: "contact@foundersgroup.vc",
    sectors: ["Mode / Luxe", "E-commerce / Retail", "Cosmétique / Beauté", "Marketplace", "DeepTech / IA"],
    stages: ["Seed", "Série A"],
    ticket_min: 300000,
    ticket_max: 5000000,
    investment_thesis: "Founders Group investit dans des startups qui transforment la mode, la beauté et le retail avec des technologies innovantes. Le fonds cherche des modèles disruptifs dans la vente directe, la personnalisation, la durabilité et la nouvelle relation entre marques et consommateurs.",
    notable_investments: "Vestiaire Collective (early), Sézane (early)",
  },
  {
    name: "Five Seasons Ventures",
    description: "VC européen spécialisé dans la FoodTech, l'AgriTech et le Future of Food.",
    website: "https://www.fiveseasonsventures.com",
    contact_email: "hello@fiveseasonsventures.com",
    sectors: ["FoodTech / AgriTech", "GreenTech / CleanTech", "Restauration / FoodService", "DeepTech / IA", "HealthTech / MedTech"],
    stages: ["Seed", "Série A"],
    ticket_min: 500000,
    ticket_max: 10000000,
    investment_thesis: "Five Seasons Ventures est le premier VC européen 100% dédié au Food & Agri. Le fonds investit dans des startups qui transforment la chaîne alimentaire mondiale : protéines alternatives, agriculture de précision, réduction du gaspillage, logistique alimentaire et nouveaux modèles de restauration.",
    notable_investments: "Ÿnsect, Umiami, Solaroad",
  },
  {
    name: "Unigrains",
    description: "Fonds d'investissement de la filière céréalière française en agriculture et agroalimentaire.",
    website: "https://www.unigrains.fr",
    contact_email: "contact@unigrains.fr",
    sectors: ["FoodTech / AgriTech", "Restauration / FoodService", "GreenTech / CleanTech", "Industrie / Manufacturing"],
    stages: ["Seed", "Série A", "Série B"],
    ticket_min: 500000,
    ticket_max: 15000000,
    investment_thesis: "Unigrains est un investisseur de référence dans les filières céréalières et agroalimentaires françaises. Le fonds soutient des entreprises innovantes dans la transformation alimentaire, l'agriculture durable, les technologies agricoles et les nouvelles protéines. Réseau unique au sein de la filière agricole française.",
    notable_investments: "Agreenculture, Terres Inovia",
  },
  {
    name: "Capagro",
    description: "VC spécialisé dans l'agriculture, l'agroalimentaire et les technologies agri.",
    website: "https://www.capagro.fr",
    contact_email: "contact@capagro.fr",
    sectors: ["FoodTech / AgriTech", "GreenTech / CleanTech", "Énergie", "Industrie / Manufacturing"],
    stages: ["Seed", "Série A"],
    ticket_min: 300000,
    ticket_max: 8000000,
    investment_thesis: "Capagro est un fonds spécialisé dans les innovations pour l'agriculture durable et l'agroalimentaire. Le fonds investit dans des startups qui apportent des solutions concrètes aux enjeux de la transition agricole : réduction des intrants, agriculture de précision, gestion de l'eau, protéines alternatives et circuits courts.",
    notable_investments: "TeleCrop, Arvalis spinoffs",
  },

  // ─────────────────────────────────────────────
  // VCs TOURISME / HÔTELLERIE / SPORT
  // ─────────────────────────────────────────────
  {
    name: "Accor Growth",
    description: "Fonds de corporate venture du groupe Accor, leader mondial de l'hôtellerie.",
    website: "https://www.accor.com",
    contact_email: "ventures@accor.com",
    sectors: ["Tourisme / Hôtellerie", "SaaS / Logiciel", "Marketplace", "Services B2B", "Mobilité / Transport"],
    stages: ["Seed", "Série A", "Série B"],
    ticket_min: 500000,
    ticket_max: 15000000,
    investment_thesis: "Accor Growth investit dans des startups qui transforment l'industrie hôtelière, du voyage et de l'expérience client. Les startups bénéficient d'un accès au réseau mondial d'Accor (5 000 hôtels dans 110 pays), de pilotes commerciaux et d'une distribution internationale dans le secteur du voyage et de l'hospitalité.",
    notable_investments: "Wojo, Onefinestay, ResDiary",
  },
  {
    name: "Tikehau Growth Equity",
    description: "Fonds growth du groupe Tikehau Capital, multi-sectoriel avec focus sur le tourisme et les services.",
    website: "https://www.tikehaucapital.com",
    contact_email: "contact@tikehaucapital.com",
    sectors: ["Tourisme / Hôtellerie", "Services B2B", "FinTech", "SaaS / Logiciel", "Tous secteurs"],
    stages: ["Série A", "Série B", "Série B+"],
    ticket_min: 5000000,
    ticket_max: 50000000,
    investment_thesis: "Tikehau Growth Equity est le fonds growth du groupe Tikehau Capital, l'un des principaux gestionnaires d'actifs alternatifs français. Le fonds investit dans des scale-ups à fort potentiel de croissance dans des secteurs diversifiés, en apportant capital patient et expertise sectorielle.",
    notable_investments: "Happyvore, Orpi Ventures",
  },
  {
    name: "Holt Fintech Accelerator",
    description: "Accélérateur FinTech franco-canadien investissant dans les innovations financières.",
    website: "https://www.holtfintech.com",
    contact_email: "contact@holtfintech.com",
    sectors: ["FinTech", "InsurTech / Assurance", "SaaS / Logiciel", "DeepTech / IA"],
    stages: ["Pre-seed", "Seed"],
    ticket_min: 150000,
    ticket_max: 500000,
    investment_thesis: "Holt Fintech est un accélérateur dédié aux startups FinTech avec une présence en France et au Canada. Le programme soutient des fondateurs développant des solutions innovantes pour la banque, les paiements, la gestion de patrimoine et l'assurance, avec accès au réseau bancaire nord-américain.",
    notable_investments: "Flinks, Hardbacon",
  },

  // ─────────────────────────────────────────────
  // VCs MEDIA / ENTERTAINMENT / GAMING
  // ─────────────────────────────────────────────
  {
    name: "Idinvest Partners (fonds historique)",
    description: "L'un des pionniers du VC européen, maintenant intégré à Eurazeo.",
    website: "https://www.eurazeo.com",
    contact_email: "venture@eurazeo.com",
    sectors: ["SaaS / Logiciel", "FinTech", "Marketplace", "E-commerce / Retail"],
    stages: ["Série A", "Série B", "Série B+"],
    ticket_min: 3000000,
    ticket_max: 40000000,
    investment_thesis: "Idinvest, maintenant Eurazeo Ventures, est l'un des pionniers du VC en France avec +20 ans d'investissement. Le fonds intervient en Série A et au-delà pour accompagner les scale-ups technologiques dans leur accélération. Priorité aux leaders de marché avec une croissance >100% par an.",
    notable_investments: "Vestiaire Collective, ManoMano, Mirakl, Kyriba",
  },
  {
    name: "Jaina Capital",
    description: "Fonds VC et holding de Marc et Éric Lagardère, spécialisé dans les médias et la tech.",
    website: "https://www.jaina.fr",
    contact_email: "contact@jaina.fr",
    sectors: ["Médias / Divertissement", "Gaming / Jeux Vidéo", "E-commerce / Retail", "SaaS / Logiciel"],
    stages: ["Seed", "Série A"],
    ticket_min: 300000,
    ticket_max: 5000000,
    investment_thesis: "Jaina Capital est le fonds d'investissement de la famille Lagardère dans la tech et les médias digitaux. Le fonds investit dans des startups innovantes dans les médias, le contenu digital, le gaming et les plateformes de divertissement. Accès unique au réseau médias du groupe Lagardère.",
    notable_investments: "Dailymotion (early), Studio+",
  },
  {
    name: "Voodoo Fund",
    description: "Fonds d'investissement du leader français du mobile gaming.",
    website: "https://www.voodoo.io",
    contact_email: "fund@voodoo.io",
    sectors: ["Gaming / Jeux Vidéo", "Médias / Divertissement", "SaaS / Logiciel", "DeepTech / IA"],
    stages: ["Pre-seed", "Seed"],
    ticket_min: 100000,
    ticket_max: 1000000,
    investment_thesis: "Voodoo Fund investit dans des studios de jeux vidéo mobiles et des startups tech liées au gaming et au divertissement interactif. Voodoo, avec +7 milliards de téléchargements, apporte une expertise unique en distribution d'apps, monétisation et croissance dans l'écosystème mobile.",
    notable_investments: "Beach Bum, Rollic",
  },

  // ─────────────────────────────────────────────
  // VCs IMMOBILIER / MOBILITÉ / INDUSTRIE
  // ─────────────────────────────────────────────
  {
    name: "Idinvest PropTech",
    description: "Branche PropTech d'Eurazeo, spécialisée dans les startups de l'immobilier et la construction.",
    website: "https://www.eurazeo.com",
    contact_email: "proptech@eurazeo.com",
    sectors: ["PropTech / Immobilier", "BTP / Construction", "GreenTech / CleanTech", "SaaS / Logiciel"],
    stages: ["Seed", "Série A", "Série B"],
    ticket_min: 1000000,
    ticket_max: 15000000,
    investment_thesis: "Ce fonds dédié investit dans des startups qui transforment l'immobilier, la construction et la ville. Technologies ciblées : gestion intelligente des bâtiments, construction modulaire, marketplaces immobilières, financement participatif immobilier et solutions de durabilité pour le parc immobilier existant.",
    notable_investments: "Masteos, Manda, Hosman",
  },
  {
    name: "SNCF Digital Ventures",
    description: "Fonds de corporate venture de SNCF, investissant dans la mobilité du futur.",
    website: "https://www.sncf.com/fr/groupe/innovations/corporate-venture",
    contact_email: "digital.ventures@sncf.fr",
    sectors: ["Mobilité / Transport", "SaaS / Logiciel", "DeepTech / IA", "GreenTech / CleanTech", "Services B2B"],
    stages: ["Seed", "Série A"],
    ticket_min: 500000,
    ticket_max: 10000000,
    investment_thesis: "SNCF Digital Ventures investit dans des startups qui révolutionnent la mobilité, la logistique et l'expérience voyageur. Les startups bénéficient de l'accès aux données et infrastructures SNCF, de pilotes à grande échelle et d'un réseau de +270 000 employés et 5 millions de voyageurs quotidiens.",
    notable_investments: "Tictactrip, Ouigo (interne), Kisio",
  },
  {
    name: "Michelin New Mobility",
    description: "Fonds de corporate venture de Michelin dans la mobilité durable et les services.",
    website: "https://www.michelin.com",
    contact_email: "newmobility@michelin.com",
    sectors: ["Mobilité / Transport", "GreenTech / CleanTech", "SaaS / Logiciel", "DeepTech / IA", "Services B2B"],
    stages: ["Série A", "Série B"],
    ticket_min: 2000000,
    ticket_max: 20000000,
    investment_thesis: "Michelin New Mobility investit dans des startups qui transforment la mobilité durable, les flottes connectées et les services liés aux pneumatiques et véhicules. Les startups accèdent au réseau de distribution mondial de Michelin, à l'expertise materials science et aux partenariats avec les constructeurs automobiles.",
    notable_investments: "Vulog, Coyote, Styxx",
  },
  {
    name: "Naxicap Partners",
    description: "Fonds de capital-développement de Natixis, accompagnant les PME et startups en croissance.",
    website: "https://www.naxicap.fr",
    contact_email: "contact@naxicap.fr",
    sectors: ["Services B2B", "SaaS / Logiciel", "HealthTech / MedTech", "Industrie / Manufacturing", "Tous secteurs"],
    stages: ["Série A", "Série B", "Série B+"],
    ticket_min: 3000000,
    ticket_max: 50000000,
    investment_thesis: "Naxicap Partners est le fonds de capital-développement de Natixis Investment Managers, accompagnant des PME et scale-ups françaises en forte croissance. Le fonds est généraliste et investit dans des entreprises avec un modèle économique solide, une équipe expérimentée et une ambition de leadership sectoriel.",
    notable_investments: "Kerridge, Stéphane Plaza Immobilier",
  },
  {
    name: "Turenne Capital",
    description: "Fonds régional multi-stratégie accompagnant des PME innovantes et des startups.",
    website: "https://www.turennecapital.com",
    contact_email: "contact@turennecapital.com",
    sectors: ["SaaS / Logiciel", "Industrie / Manufacturing", "Services B2B", "HealthTech / MedTech", "Tous secteurs"],
    stages: ["Seed", "Série A", "Série B"],
    ticket_min: 500000,
    ticket_max: 15000000,
    investment_thesis: "Turenne Capital est un groupe de gestion indépendant spécialisé dans le capital-innovation et le capital-développement pour des PME françaises. Le fonds accompagne des entreprises avec des modèles éprouvés dans des secteurs diversifiés et cherche des champions sectoriels régionaux.",
    notable_investments: "HighCo, Solutions 30",
  },
  {
    name: "Sofimac Partners",
    description: "VC régional spécialisé Auvergne-Rhône-Alpes, tous secteurs innovants.",
    website: "https://www.sofimac-innovation.com",
    contact_email: "contact@sofimac-innovation.com",
    sectors: ["DeepTech / IA", "HealthTech / MedTech", "Industrie / Manufacturing", "SaaS / Logiciel", "GreenTech / CleanTech"],
    stages: ["Pre-seed", "Seed", "Série A"],
    ticket_min: 100000,
    ticket_max: 3000000,
    investment_thesis: "Sofimac Partners est le VC de référence de la région Auvergne-Rhône-Alpes, investissant dans des startups innovantes de tous secteurs. Le fonds bénéficie d'un réseau dense d'industriels, chercheurs et entrepreneurs régionaux ainsi que d'un partenariat fort avec les écosystèmes d'innovation de Lyon et Grenoble.",
    notable_investments: "Entrapping, VulcanO",
  },

  // ─────────────────────────────────────────────
  // VCs EUROPÉENS ACTIFS EN FRANCE
  // ─────────────────────────────────────────────
  {
    name: "Speedinvest",
    description: "VC européen early-stage avec une présence active à Paris.",
    website: "https://www.speedinvest.com",
    contact_email: "hello@speedinvest.com",
    sectors: ["FinTech", "SaaS / Logiciel", "DeepTech / IA", "HealthTech / MedTech", "Marketplace"],
    stages: ["Pre-seed", "Seed"],
    ticket_min: 200000,
    ticket_max: 3000000,
    investment_thesis: "Speedinvest est un VC européen early-stage avec des bureaux dans 7 villes dont Paris. Le fonds investit dans des startups en pré-seed et seed dans des secteurs clés : FinTech, SaaS B2B, HealthTech et DeepTech. Speedinvest apporte un accompagnement opérationnel intense avec des équipes spécialisées par secteur.",
    notable_investments: "Bitpanda, GoStudent, Lassie",
  },
  {
    name: "Heartcore Capital",
    description: "VC européen spécialisé dans les startups consumer et marketplace.",
    website: "https://www.heartcore.vc",
    contact_email: "hello@heartcore.vc",
    sectors: ["Marketplace", "E-commerce / Retail", "SaaS / Logiciel", "FinTech", "Mode / Luxe"],
    stages: ["Seed", "Série A"],
    ticket_min: 500000,
    ticket_max: 8000000,
    investment_thesis: "Heartcore Capital est un VC européen spécialisé dans les startups consumer-facing et marketplace. Le fonds investit dans des fondateurs qui créent des expériences utilisateur exceptionnelles et construisent des marques fortes. Heartcore a une thèse forte sur les nouveaux comportements de consommation en Europe.",
    notable_investments: "Peakon, Vivino, Perkbox",
  },
  {
    name: "Samaipata Ventures",
    description: "VC pan-européen spécialisé dans les plateformes et marketplaces.",
    website: "https://www.samaipata.vc",
    contact_email: "hello@samaipata.vc",
    sectors: ["Marketplace", "SaaS / Logiciel", "FinTech", "E-commerce / Retail", "Mobilité / Transport"],
    stages: ["Pre-seed", "Seed"],
    ticket_min: 200000,
    ticket_max: 2000000,
    investment_thesis: "Samaipata Ventures est un VC spécialisé dans les plateformes à effets de réseau et les marketplaces. Le fonds s'intéresse aux startups qui créent de nouveaux marchés ou désintermédient des secteurs traditionnels en Europe, en utilisant des mécanismes de croissance virale et des modèles avec des barrières naturelles à l'entrée.",
    notable_investments: "Dietox, Bob W, Freepik",
  },
  {
    name: "Point Nine Capital",
    description: "VC berlinois très actif en France, spécialisé dans le SaaS et les marketplaces.",
    website: "https://www.pointnine.com",
    contact_email: "contact@pointnine.com",
    sectors: ["SaaS / Logiciel", "Marketplace", "FinTech", "DeepTech / IA"],
    stages: ["Seed", "Série A"],
    ticket_min: 500000,
    ticket_max: 5000000,
    investment_thesis: "Point Nine Capital est un VC berlinois de référence pour les startups SaaS B2B et marketplace européennes. Le fonds a développé une expertise unique dans l'évaluation des métriques SaaS et marketplace. Point Nine investit activement en France et accompagne les startups dans leur expansion internationale.",
    notable_investments: "Zendesk (early), Delivery Hero (early), Loom (early)",
  },
  {
    name: "Seedcamp",
    description: "Premier accélérateur-VC pan-européen, soutien dès la pré-émergence.",
    website: "https://www.seedcamp.com",
    contact_email: "hello@seedcamp.com",
    sectors: ["SaaS / Logiciel", "FinTech", "DeepTech / IA", "Marketplace", "Tous secteurs"],
    stages: ["Pre-seed", "Seed"],
    ticket_min: 100000,
    ticket_max: 500000,
    investment_thesis: "Seedcamp est le premier accélérateur pan-européen, ayant soutenu +500 startups depuis 2007. Le programme offre capital, accompagnement et accès à un réseau mondial de mentors et d'investisseurs. Seedcamp investit dans des fondateurs exceptionnels avec ambition globale, tous secteurs confondus.",
    notable_investments: "Wise (TransferWise), Revolut (early), UiPath (early)",
  },
  {
    name: "Earlybird Venture Capital",
    description: "VC allemand de référence, très actif dans les startups DeepTech françaises.",
    website: "https://www.earlybird.com",
    contact_email: "contact@earlybird.com",
    sectors: ["DeepTech / IA", "HealthTech / MedTech", "SaaS / Logiciel", "FinTech", "Cybersécurité"],
    stages: ["Seed", "Série A", "Série B"],
    ticket_min: 1000000,
    ticket_max: 20000000,
    investment_thesis: "Earlybird est l'un des VCs européens les plus actifs avec +30 ans d'expérience et des bureaux à Berlin, Munich, Istanbul et une présence forte à Paris. Le fonds cible des startups tech ambitieuses avec une technologie différenciante, notamment dans la DeepTech, l'IA, la HealthTech et le SaaS B2B.",
    notable_investments: "UiPath, N26 (early), SumUp (early)",
  },

  // ─────────────────────────────────────────────
  // FONDS IMPACT & ESG
  // ─────────────────────────────────────────────
  {
    name: "Mirova Venture",
    description: "Fonds VC d'impact de Natixis IM, spécialisé dans la transition écologique.",
    website: "https://www.mirova.com",
    contact_email: "contact@mirova.com",
    sectors: ["GreenTech / CleanTech", "Énergie", "FoodTech / AgriTech", "Mobilité / Transport", "DeepTech / IA"],
    stages: ["Série A", "Série B"],
    ticket_min: 2000000,
    ticket_max: 20000000,
    investment_thesis: "Mirova est le gestionnaire d'actifs durables de Natixis Investment Managers. Son fonds venture investit dans des entreprises qui apportent des solutions concrètes aux défis climatiques et environnementaux. Strict respect des critères ESG et mesure rigoureuse de l'impact positif pour chaque investissement.",
    notable_investments: "Lhyfe, Enerprag, Elogen",
  },
  {
    name: "Shift4Good",
    description: "Fonds impact spécialisé dans les startups de la mobilité durable.",
    website: "https://www.shift4good.com",
    contact_email: "contact@shift4good.com",
    sectors: ["Mobilité / Transport", "GreenTech / CleanTech", "Énergie", "DeepTech / IA"],
    stages: ["Seed", "Série A", "Série B"],
    ticket_min: 500000,
    ticket_max: 15000000,
    investment_thesis: "Shift4Good est un fonds d'impact spécialisé dans la transformation durable du secteur de la mobilité. Le fonds investit dans des startups qui réduisent l'empreinte carbone des transports : véhicules électriques, mobilité partagée, logistique verte, infrastructure de recharge et technologies d'optimisation des déplacements.",
    notable_investments: "Mob-Ion, Electra, Zenride",
  },
  {
    name: "Schneider Electric Ventures",
    description: "Bras VC de Schneider Electric, spécialisé dans l'efficacité énergétique et l'industrie 4.0.",
    website: "https://www.se.com/fr/fr/about-us/innovation/se-ventures.jsp",
    contact_email: "seventures@se.com",
    sectors: ["Énergie", "Industrie / Manufacturing", "SaaS / Logiciel", "DeepTech / IA", "GreenTech / CleanTech"],
    stages: ["Série A", "Série B"],
    ticket_min: 2000000,
    ticket_max: 20000000,
    investment_thesis: "SE Ventures investit dans des startups qui accélèrent la transition énergétique et la numérisation industrielle. Les startups bénéficient de l'accès au réseau mondial de Schneider Electric (présent dans 100+ pays), de pilotes dans des datacenters, usines et bâtiments connectés, et d'une expertise unique en énergie.",
    notable_investments: "Claroty, Sense, AutoGrid",
  },
  {
    name: "Epopea",
    description: "Fonds VC early-stage focalisé sur les startups B2B et les marchés de niche.",
    website: "https://www.epopea.co",
    contact_email: "hello@epopea.co",
    sectors: ["SaaS / Logiciel", "Marketplace", "Services B2B", "FinTech", "LegalTech / RegTech"],
    stages: ["Pre-seed", "Seed"],
    ticket_min: 100000,
    ticket_max: 1000000,
    investment_thesis: "Epopea est un micro-VC français qui investit très tôt dans des startups B2B cherchant à devenir des références dans des marchés de niche. Le fonds cible des fondateurs avec une expertise sectorielle profonde qui construisent des solutions verticales difficiles à répliquer.",
    notable_investments: "Skalin, Eolane, Plume",
  },
  {
    name: "Latitude Ventures",
    description: "VC deep tech soutenu par des scientifiques et ingénieurs de haut niveau.",
    website: "https://www.latitude.vc",
    contact_email: "contact@latitude.vc",
    sectors: ["DeepTech / IA", "HealthTech / MedTech", "Cybersécurité", "Industrie / Manufacturing", "GreenTech / CleanTech"],
    stages: ["Pre-seed", "Seed"],
    ticket_min: 200000,
    ticket_max: 3000000,
    investment_thesis: "Latitude est un fonds fondé par des scientifiques et ingénieurs qui investissent dans les startups deeptech les plus prometteuses. Le fonds cible des innovations issues de la recherche académique française avec des applications industrielles à fort potentiel, notamment dans l'IA, la physique quantique, la biologie computationnelle et les matériaux avancés.",
    notable_investments: "Alice & Bob, Pasqal, LightOn",
  },
  {
    name: "ACE Capital Partners",
    description: "Fonds de capital-investissement growth spécialisé dans les services et la tech.",
    website: "https://www.acecapitalpartners.com",
    contact_email: "contact@acecapitalpartners.com",
    sectors: ["Services B2B", "SaaS / Logiciel", "RH / Recrutement", "FinTech", "Industrie / Manufacturing"],
    stages: ["Série A", "Série B"],
    ticket_min: 3000000,
    ticket_max: 30000000,
    investment_thesis: "ACE Capital Partners est spécialisé dans le capital-développement de PME et scale-ups françaises dans les services à forte valeur ajoutée et la tech. Le fonds accompagne des entreprises avec des business models éprouvés dans une logique de build-up sectoriel et d'internationalisation.",
    notable_investments: "Webhelp, Intelcia",
  },
  {
    name: "Robolution Capital",
    description: "VC européen unique, 100% dédié aux startups de la robotique et du hardware.",
    website: "https://www.robolutioncapital.com",
    contact_email: "contact@robolutioncapital.com",
    sectors: ["DeepTech / IA", "Industrie / Manufacturing", "HealthTech / MedTech", "Mobilité / Transport", "GreenTech / CleanTech"],
    stages: ["Seed", "Série A"],
    ticket_min: 500000,
    ticket_max: 10000000,
    investment_thesis: "Robolution Capital est le premier fonds européen dédié à la robotique. Le fonds investit dans des startups qui construisent des robots et systèmes autonomes pour l'industrie, la santé, l'agriculture et les services. L'équipe apporte une expertise technique unique dans le hardware, les capteurs et les systèmes embarqués.",
    notable_investments: "Exotec, Wyca Robotics, MC2 Robotics",
  },
  {
    name: "InVivo Ventures",
    description: "Fonds d'investissement du groupe agricole InVivo dans les AgriTech et FoodTech.",
    website: "https://www.invivo-group.com/fr/invivo-ventures",
    contact_email: "ventures@invivo-group.com",
    sectors: ["FoodTech / AgriTech", "GreenTech / CleanTech", "DeepTech / IA", "Restauration / FoodService"],
    stages: ["Seed", "Série A", "Série B"],
    ticket_min: 500000,
    ticket_max: 10000000,
    investment_thesis: "InVivo Ventures est le bras d'investissement du groupe coopératif agricole InVivo, premier groupe coopératif agricole français. Le fonds accompagne des startups innovantes dans l'agriculture durable, les nouvelles protéines, la distribution alimentaire et la digitalisation des filières agricoles.",
    notable_investments: "Solynta, VGF Cosucra",
  },
];

async function seedVCs() {
  console.log(`Début du seeding — ${VCS_FRANCAIS.length} VCs à insérer...\n`);
  let success = 0;
  let errors = 0;

  for (const vc of VCS_FRANCAIS) {
    const { data, error } = await supabase
      .from("venture_capitals")
      .upsert(vc, { onConflict: "name" })
      .select()
      .single();

    if (error) {
      console.error(`✗ ${vc.name}: ${error.message}`);
      errors++;
    } else {
      console.log(`✓ ${vc.name}`);
      success++;
    }
  }

  console.log(`\n✅ ${success} VCs seedés avec succès !`);
  if (errors > 0) console.log(`⚠️  ${errors} erreurs`);
}

seedVCs().catch(console.error);
